'use client';
import {useEffect,useState} from 'react';
import {Plus,Save,Send,Upload,Search} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Article,ArticleBlock,ArticleKind,newArticle} from '@/lib/site-content';
import {Card,CATALOG_VERSION} from '@/lib/cards';
import {Choice} from '../atlas';
import ArticleContent from '../article-content';
import {useSiteContent} from '../site-provider';
const names={rule:'规则',world:'世界观',character:'角色'};
export default function ArticleEditor({kind,characters}:{kind:ArticleKind;characters:Card[]}){
 const {reload:reloadPublic}=useSiteContent();const [items,setItems]=useState<Article[]>([]),[current,setCurrent]=useState<Article|null>(null),[query,setQuery]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState<Article|null>(null);
 async function load(){try{const r=await fetch('/api/admin/content',{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw new Error(j.error);if(j.catalogVersion!==CATALOG_VERSION)throw new Error('编号正在更新，请稍后刷新页面。');const next=j.articles.filter((a:Article)=>a.kind===kind);setItems(next);if(!current)setCurrent(next[0]||newArticle(kind));else{const found=next.find((a:Article)=>a.id===current.id);if(found)choose(found)}setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[]);useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',before);return()=>removeEventListener('beforeunload',before)},[dirty]);
 function choose(a:Article){if(dirty)setPending(a);else{setCurrent(structuredClone(a));setDirty(false);setError('');setMessage('')}}
 function put(key:string,value:any){setCurrent(c=>c?{...c,[key]:value}:c);setDirty(true);setMessage('')}
 function block(id:string,values:Partial<ArticleBlock>){put('blocks',current?.blocks.map(b=>b.id===id?{...b,...values}:b)||[])}
 function add(type:ArticleBlock['type']){if(!current)return;put('blocks',[...current.blocks,{id:crypto.randomUUID(),type,text:''}])}
 function move(index:number,direction:number){if(!current)return;const next=[...current.blocks];[next[index],next[index+direction]]=[next[index+direction],next[index]];put('blocks',next)}
 async function upload(id:string,file?:File){if(!file)return;if(file.size>8*1024*1024){setError('图片不得超过8MB。');return}setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:form});const j:any=await r.json();if(!r.ok)throw new Error(j.error);block(id,{url:j.url});setMessage('图片已上传，发布文章后访客可见。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(action:string){if(!current)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,item:current,revision:current.revision||0,action,catalogVersion:CATALOG_VERSION})});const j:any=await r.json();if(!r.ok)throw new Error(j.error);setCurrent(j.item);setItems(all=>all.some(a=>a.id===j.item.id)?all.map(a=>a.id===j.item.id?j.item:a):[...all,j.item]);setDirty(false);setMessage(j.message);if(action==='publish')reloadPublic()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="editor-layout article-workspace"><aside className="editor-list"><button className="gold-button" disabled={busy} onClick={()=>choose(newArticle(kind,items.length))}><Plus size={17}/>新增{names[kind]}条目</button><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label={`搜索${names[kind]}条目`} placeholder="查找条目…"/></label><div className="editor-records">{items.filter(a=>a.title.includes(query)).map(a=><button key={a.id} disabled={busy} className={current?.id===a.id?'selected':''} onClick={()=>choose(a)}><span>{a.title}</span>{a.hasDraft&&<i>草稿</i>}</button>)}</div></aside><section className="editor-form">{error&&<div className="notice" role="alert">{error}<button onClick={load} disabled={busy}>载入最新草稿</button></div>}{current?<><div className="editor-status"><span>{dirty?'有未保存修改':current.hasDraft?'草稿已保存，尚未发布':current.published?'已发布':'尚未发布'}</span><span>文字、标题与图片可自由编排</span></div><fieldset disabled={busy}><div className="edit-row"><label className="edit-label"><span>条目标题</span><input value={current.title} onChange={e=>put('title',e.target.value)} maxLength={120}/></label><label className="edit-label"><span>排序序号</span><input type="number" min={0} max={9999} value={current.order} onChange={e=>put('order',Number(e.target.value))}/></label></div>{kind==='character'&&<div style={{marginTop:20}}><Choice label="所属魔女" value={current.characterId||'unselected'} onChange={v=>put('characterId',v==='unselected'?undefined:v)} options={[["unselected","选择角色"],...characters.map(c=>[c.id,c.name] as [string,string])]}/></div>}<label className="edit-label" style={{marginTop:22}}><span>文章摘要</span><textarea rows={2} maxLength={2000} value={current.summary} onChange={e=>put('summary',e.target.value)}/></label>
 {current.blocks.map((b,i)=><div className="article-block-editor" key={b.id}><div className="block-tools"><span>{i+1} · {b.type==='image'?'图片':b.type==='heading'?'章节标题':'文字段落'}</span><div><button type="button" aria-label={`上移第${i+1}段`} disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button type="button" aria-label={`下移第${i+1}段`} disabled={i===current.blocks.length-1} onClick={()=>move(i,1)}>↓</button><button type="button" aria-label={`删除第${i+1}段`} onClick={()=>put('blocks',current.blocks.filter(x=>x.id!==b.id))}>移除</button></div></div>{b.type==='image'?<>{b.url&&<img src={b.url} alt={b.caption||'文章图片预览'}/>}<label className="outline-button upload-label"><Upload size={15}/>{b.url?'替换图片':'上传图片'}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" aria-label={`第${i+1}段图片`} onChange={e=>upload(b.id,e.target.files?.[0])}/></label><label className="edit-label"><span>图片说明</span><input value={b.caption||''} onChange={e=>block(b.id,{caption:e.target.value})}/></label></>:<label className="edit-label"><span className="sr-only">第{i+1}段内容</span><textarea rows={b.type==='heading'?2:6} value={b.text||''} onChange={e=>block(b.id,{text:e.target.value})} placeholder={b.type==='heading'?'输入章节标题':'在这里写下文章正文…'}/></label>}</div>)}
 <div className="block-add"><button type="button" className="outline-button" onClick={()=>add('paragraph')}><Plus size={15}/>添加段落</button><button type="button" className="outline-button" onClick={()=>add('heading')}>添加标题</button><button type="button" className="outline-button" onClick={()=>add('image')}><Upload size={15}/>添加图片</button></div></fieldset><details className="article-preview"><summary>展开文章预览</summary><ArticleContent article={current}/></details><div className="editor-actions"><span className="help" role="status">{busy?'正在保存…':message||'发布后显示在对应板块'}</span><button className="outline-button" disabled={busy||!current.title} onClick={()=>save('save')}><Save size={16}/>保存草稿</button><button className="gold-button" disabled={busy||!current.title} onClick={()=>save('publish')}><Send size={16}/>发布文章</button></div></>:<p className="help">正在读取文章…</p>}</section><AlertDialog open={!!pending} onOpenChange={v=>{if(!v)setPending(null)}}><AlertDialogContent><AlertDialogTitle>离开未保存的文章？</AlertDialogTitle><AlertDialogDescription>继续切换会放弃当前未保存的修改。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>继续编辑</AlertDialogCancel><AlertDialogAction onClick={()=>{if(pending)setCurrent(structuredClone(pending));setPending(null);setDirty(false);setError('');setMessage('')}}>放弃并切换</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
