'use client';
import {useState,useEffect} from 'react';
import {Mail,ShieldCheck} from 'lucide-react';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
export default function EmailLogin(){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[error,setError]=useState('');
 useEffect(()=>{if(!retry)return;const timer=setInterval(()=>setRetry(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[retry>0]);
 async function send(){setBusy(true);setError('');try{const r=await fetch('/api/auth/send-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const j:any=await r.json();if(j.retryAfter)setRetry(j.retryAfter);if(!r.ok)throw new Error(j.error);setSent(true);setCode('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/verify-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const j:any=await r.json();if(!r.ok)throw new Error(j.error);location.assign('/admin')}catch(e){setError((e as Error).message);setBusy(false)}}
 return <div className="login-panel"><p className="eyebrow">THE KEEPER'S DESK</p><h1>邮箱验证码登录</h1><p>使用已指定的管理员邮箱，接收一次性验证码。</p><form className="otp-form" onSubmit={verify}><div className="otp-email-row"><label className="edit-label"><span>管理员邮箱</span><input type="email" autoComplete="email" required value={email} onChange={e=>{setEmail(e.target.value);setSent(false);setCode('')}} placeholder="输入管理员邮箱" disabled={busy}/></label><button type="button" className="outline-button" onClick={send} disabled={busy||retry>0||!email}><Mail size={16}/>{retry>0?`${retry}秒后重发`:sent?'重新发送':'发送验证码'}</button></div>{sent&&<><label className="edit-label"><span>6位验证码</span><InputOTP containerClassName="otp-slots" aria-label="6位验证码" maxLength={6} pattern="^[0-9]*$" value={code} onChange={setCode} disabled={busy} autoComplete="one-time-code"><InputOTPGroup>{Array.from({length:6},(_,i)=><InputOTPSlot index={i} key={i}/>)}</InputOTPGroup></InputOTP></label><p className="help" role="status">验证码已发送，10分钟内有效。未收到时请检查垃圾邮件。</p><button className="gold-button" disabled={busy||code.length!==6}><ShieldCheck size={17}/>{busy?'正在验证…':'验证并进入后台'}</button></>}{error&&<p className="notice" role="alert">{error}</p>}</form><a className="text-link" href="/">返回卡牌图鉴</a></div>;
}
