'use client';
import {useState,useEffect} from 'react';
import {Save,Send} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {CardFormat,DisplaySettings,defaultSettings} from '@/lib/site-content';
import {categories,seedCards} from '@/lib/cards';
import {CardFace} from '../card-components';
import {useSiteContent} from '../site-provider';
import RangeField from './range-field';
export default function SettingsEditor(){
 const {reload}=useSiteContent();const [value,setValue]=useState<DisplaySettings>(defaultSettings),[revision,setRevision]=useState(0),[selected,setSelected]=useState('basic'),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/admin/content',{cache:'no-store'}).then(async r=>{const j:any=await r.json();if(!r.ok)throw new Error(j.error);setValue(j.settings);setRevision(j.settingsRevision);setMessage(j.settingsHasDraft?'已载入未发布草稿':'当前为已发布参数')}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',before);return()=>removeEventListener('beforeunload',before)},[dirty]);
 function update(v:DisplaySettings){setValue(v);setDirty(true);setMessage('参数尚未保存')}
 function format(id:string,key:keyof CardFormat,n:number){setSelected(id);update({...value,formats:{...value.formats,[id]:{...value.formats[id],[key]:n}}})}
 async function save(action:string){setBusy(true);setError('');try{const r=await fetch('/api/admin/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'settings',item:value,revision,action})});const j:any=await r.json();if(!r.ok)throw new Error(j.error);setRevision(j.item.revision);setDirty(false);setMessage(j.message);if(action==='publish')reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="format-settings"><section className="editor-form"><p className="format-help">尺寸按“高度 × 宽度”设置。图片按比例填充，超出边缘的部分自动裁切；圆角以毫米为单位等比缩放。侧栏卡图宽度用于桌面并排展示。</p>{error&&<p className="notice" role="alert">{error}</p>}<fieldset disabled={busy}><div className="format-list">{categories.map(([id,name])=><section className={'format-row '+(selected===id?'active':'')} key={id}><h3>{name}<button type="button" onClick={()=>setSelected(id)}>查看比例</button></h3><div className="editor-fields">{([['height','高度 mm',10,500],['width','宽度 mm',10,400],['radius','圆角 mm',0,20],['previewWidth','侧栏宽度 px',80,320]] as const).map(([key,label,min,max])=><label className="edit-label" key={key}><span>{label}</span><input type="number" min={min} max={max} step={key==='previewWidth'?1:0.5} value={value.formats[id][key]} onChange={e=>format(id,key,Math.min(max,Math.max(min,Number(e.target.value))))}/></label>)}</div></section>)}</div><div className="motion-settings"><label className="check-label"><Checkbox checked={value.motion} onCheckedChange={checked=>update({...value,motion:checked===true})}/>启用流光、雾气与鼠标视差</label><RangeField label="虹彩流光强度" value={value.glow} onChange={glow=>update({...value,glow})} suffix="%"/><RangeField label="氛围雾气强度" value={value.fog} onChange={fog=>update({...value,fog})} suffix="%"/><p className="help">访客设备开启“减少动态效果”时，自动降低动效。</p></div></fieldset><div className="editor-actions"><span className="help" role="status">{message}</span><button className="outline-button" disabled={busy} onClick={()=>save('save')}><Save size={16}/>保存草稿</button><button className="gold-button" disabled={busy} onClick={()=>save('publish')}><Send size={16}/>发布参数</button></div></section><aside className="format-preview"><CardFace card={seedCards.find(c=>c.categoryId===selected)!} format={value.formats[selected]}/><p>{value.formats[selected].height} × {value.formats[selected].width} mm<br/>圆角 {value.formats[selected].radius} mm</p></aside></div>;
}
