'use client';
import {useEffect,useState,useMemo} from 'react';
import {Search,SlidersHorizontal,RotateCcw,ArrowUpRight,BookOpen,ChevronLeft,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTrigger,SheetTitle} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Header,Footer} from './chrome';
import {Card,seedCards,categories,effects,categoryName,cardAttribute,searchText,CATALOG_VERSION} from '@/lib/cards';
import {Tile,CardFace,CardDetails,Specialty} from './card-components';
import rulesSource from '@/data/source-rules.json';
import SpecialEntry from './special-entry';
const all='all';
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="select-label"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,n])=><SelectItem value={v} key={v}>{n}</SelectItem>)}</SelectContent></Select></label>}
export default function Atlas({initialId,mode='cards'}:{initialId?:string;mode?:'cards'|'character'|'detail'}){
const [data,setData]=useState<Card[]>(seedCards),[loading,setLoading]=useState(true),[error,setError]=useState('');const [category,setCategory]=useState('basic'),[query,setQuery]=useState(''),[type,setType]=useState(all),[cost,setCost]=useState(all),[attribute,setAttribute]=useState(all),[debuff,setDebuff]=useState(all),[piercing,setPiercing]=useState(all),[effect,setEffect]=useState<string[]>([]),[prereq,setPrereq]=useState(all),[condition,setCondition]=useState(''),[sort,setSort]=useState('source'),[limit,setLimit]=useState(24);const [selected,setSelected]=useState<string|null>(initialId||null);
async function reload(){setLoading(true);try{const r=await fetch('/api/cards',{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw new Error(j.error);if(j.catalogVersion!==CATALOG_VERSION)throw new Error('编号正在更新，请稍后刷新页面。');setData(j.cards);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
useEffect(()=>{reload();const timer=setInterval(reload,60000);const onFocus=()=>reload();window.addEventListener('focus',onFocus);return()=>{clearInterval(timer);window.removeEventListener('focus',onFocus)}},[]);
function reset(){setQuery('');setType(all);setCost(all);setAttribute(all);setDebuff(all);setPiercing(all);setEffect([]);setPrereq(all);setCondition('');setLimit(24)}
const activeFilters=[type,cost,attribute,debuff,piercing,prereq].filter(x=>x!==all).length+effect.length+(condition?1:0);
const filtered=useMemo(()=>{const flags=(v:any,f:string)=>f===all||f==='yes'&&v===true||f==='no'&&v===false||f==='unknown'&&(v==null);let cards=data.filter(c=>c.categoryId===category&&(!query||searchText(c).includes(query.toLowerCase()))&&(type===all||c.cardType===type)&&(cost===all||cost==='7+'&&Number(c.cost)>=7||String(c.cost)===cost)&&(attribute===all||cardAttribute(c).includes(attribute))&&flags(c.debuffFlag,debuff)&&flags(c.piercingFlag,piercing)&&effect.every(x=>c.effectTypes?.includes(x))&&(prereq===all||prereq==='yes'&&c.prerequisite||prereq==='no'&&!c.prerequisite)&&(!condition||String(c.prerequisite||'').includes(condition)));if(sort==='name')cards.sort((a,b)=>a.name.localeCompare(b.name,'zh'));if(sort==='cost')cards.sort((a,b)=>Number(a.cost??999)-Number(b.cost??999));if(category==='bounty'||sort==='difficulty'){const order:any={'低':0,'中':1,'高':2,'需结合局面':3};cards.sort((a,b)=>(order[a.bounty?.difficulty]??3)-(order[b.bounty?.difficulty]??3))}return cards},[data,category,query,type,cost,attribute,debuff,piercing,effect,prereq,condition,sort]);
useEffect(()=>setLimit(24),[category,query,type,cost,attribute,debuff,piercing,effect,prereq,condition,sort]);
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ctl=new AbortController();try{Promise.resolve(ctx.registerTool({name:'filter_card_atlas',title:'筛选魔女狂猎图鉴',description:'按牌系和文字筛选图鉴，并更新当前页面。',inputSchema:{type:'object',properties:{category:{type:'string',enum:categories.map(x=>x[0])},query:{type:'string',maxLength:200}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!categories.some(x=>x[0]===input?.category)||input.query!==undefined&&(typeof input.query!=='string'||input.query.length>200))throw new Error('无效筛选');reset();setCategory(input.category);setQuery(input.query||'');return {category:input.category,query:input.query||'',count:data.filter(c=>c.categoryId===input.category&&searchText(c).includes((input.query||'').toLowerCase())).length}}},{signal:ctl.signal})).catch(()=>{})}catch{}return()=>ctl.abort()},[data]);
const current=data.find(c=>c.id===selected);function open(c:Card){if(c.categoryId==='witch'){window.location.assign(`/characters/${c.id}`);return}setSelected(c.id);history.replaceState(null,'',`/?card=${c.id}`)}
useEffect(()=>{if(!initialId)setSelected(new URLSearchParams(location.search).get('card'))},[initialId]);
const filterUI=<><div className="filter-heading"><h2><SlidersHorizontal size={17}/>筛选卡牌</h2><button aria-label="清空筛选" onClick={reset}><RotateCcw size={15}/></button></div><div className="filter-group"><h3>卡牌类型</h3>{[[all,'全部类型'],['即时魔法','即时魔法'],['永续魔法','永续魔法']].map(([v,n])=><button className={'filter-option '+(type===v?'selected':'')} key={v} onClick={()=>setType(v)}>{n}</button>)}</div><div className="filter-group"><h3>魔晶费用</h3><div className="cost-options">{[all,'0','1','2','3','4','5','6','7+'].map(x=><button aria-pressed={cost===x} className={cost===x?'selected':''} key={x} onClick={()=>setCost(x)}>{x===all?'全部':x}</button>)}</div></div><div className="filter-group"><h3>卡牌属性</h3><div className="attributes">{[all,'火','木','水','星','邪','异','虚','任意'].map(x=><button aria-pressed={attribute===x} className={attribute===x?'selected':''} key={x} onClick={()=>setAttribute(x)}>{x===all?'全部':`✦ ${x}`}</button>)}</div></div><div className="filter-group"><h3>效果类型</h3>{effects.map(x=><label className="check-label" key={x}><Checkbox checked={effect.includes(x)} onCheckedChange={v=>setEffect(v?[...effect,x]:effect.filter(a=>a!==x))}/>{x}</label>)}</div><div className="filter-group"><Choice label="减益标记" value={debuff} onChange={setDebuff} options={[[all,'全部'],['yes','有减益'],['no','明确无减益'],['unknown','未标注']]}/><Choice label="护盾穿透" value={piercing} onChange={setPiercing} options={[[all,'全部'],['yes','有穿透'],['no','明确无穿透'],['unknown','未标注']]}/></div><div className="filter-group"><Choice label="前置条件" value={prereq} onChange={setPrereq} options={[[all,'全部'],['yes','有前置'],['no','无前置']]}/><input className="field" aria-label="前置条件关键词" placeholder="条件关键词，例如 1邪" value={condition} onChange={e=>setCondition(e.target.value)}/></div><p className="filter-note">效果标签依据卡牌文字整理。未写明的标记保留为“未标注”。</p></>;
if(mode==='character'||mode==='detail')return <div className="atlas-shell"><Header active={mode==='character'?'world':'cards'}/><main className="main detail-page"><a className="back-link" href={mode==='character'?'/world':'/'}>{mode==='character'?'← 返回角色与世界观':'← 返回卡牌图鉴'}</a>{current?<div className="character-layout"><CardDetails card={current} character={mode==='character'}/><div className="detail-art"><CardFace card={current} large/></div></div>:<p>{loading?'正在读取档案…':mode==='character'?'未找到这个角色。':'未找到这张卡牌。'}</p>}{error&&<p role="alert" className="notice">{error}</p>}</main><Footer/></div>;
return <div className="atlas-shell"><Header/><main className="main"><div className="page-intro"><div><p className="eyebrow">THE ARCANE ARCHIVE <span>／ V4</span></p><h1>卡牌图鉴<span>Card Codex</span></h1><p className="muted">翻开魔法的记忆，寻找属于你的制胜之道。</p></div><div className="edition"><span>收录卡牌</span><strong>{data.length}</strong><span>七大牌系 · 完整效果原文</span></div></div><Tabs value={category} onValueChange={v=>{setCategory(v);reset()}}><TabsList className="category-tabs">{categories.map(([id,n])=><TabsTrigger key={id} value={id}>{n}<small>{data.filter(c=>c.categoryId===id).length}</small></TabsTrigger>)}</TabsList></Tabs>{error&&<div role="alert" className="notice">{error} 当前显示随站初始资料。<button onClick={reload}>重试</button></div>}<div className="collection-layout"><aside className="filters">{['basic','forbidden'].includes(category)?filterUI:<div className="category-context"><BookOpen size={23}/><h2>{categoryName(category)}</h2><p>{rulesSource.cardTypes.find(c=>c.id===category)?.summary}</p>{rulesSource.cardTypes.find(c=>c.id===category)?.rules.map((r,i)=><p key={i}>{r}</p>)}<a className="text-link" href="/rules">查阅完整规则 →</a></div>}</aside><section className="collection"><div className="collection-toolbar"><label className="search"><Search size={18}/><input aria-label="搜索卡牌" placeholder="搜索卡牌名称、效果或关键词…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="muted">共 <b>{filtered.length}</b> 张</span><Choice label="排序" value={sort} onChange={setSort} options={[["source","原始顺序"],["name","名称排序"],["cost","费用从低到高"]]}/>{['basic','forbidden'].includes(category)&&<Sheet><SheetTrigger className="mobile-filter outline-button"><SlidersHorizontal size={15}/>筛选{activeFilters?` · ${activeFilters}`:''}</SheetTrigger><SheetContent side="left" className="filter-sheet"><SheetTitle>卡牌筛选</SheetTitle><div>{filterUI}</div></SheetContent></Sheet>}</div>{activeFilters>0&&<button className="clear-filter" onClick={reset}>清除 {activeFilters} 项筛选 ×</button>}{category==='bounty'&&<p className="category-note">完整悬赏库 {data.filter(c=>c.categoryId==='bounty').length} 张，每局随机展示5张，领取后不补充。按数值门槛作粗略排序，难度非官方判定。</p>}{category==='witch'&&<p className="category-note">查看技能速览，点击进入完整角色档案。</p>}{category==='tea'&&<p className="category-note">排名奖励及人数调整以各张牌的原文为准。</p>}
{filtered.length===0?<div className="empty-state"><Search size={32}/><h2>没有匹配的卡牌</h2><p>试试减少筛选条件，或换一个关键词。</p><button className="gold-button" onClick={reset}>重置筛选</button></div>:['basic','forbidden'].includes(category)?<div className="card-grid">{filtered.slice(0,limit).map(c=><Tile key={c.id} card={c} onClick={()=>open(c)}/>)}</div>:<div className={'special-grid '+(category==='temple'||category==='tea'?'wide':'')}>{filtered.slice(0,limit).map((c,i)=><SpecialEntry key={c.id} card={c} index={i} onOpen={()=>open(c)}/>)}</div>}{limit<filtered.length&&<div className="load-more"><button className="outline-button" onClick={()=>setLimit(limit+24)}>继续查看 · 已显示 {Math.min(limit,filtered.length)} / {filtered.length}</button></div>}</section></div></main><Footer/><Dialog open={!!current} onOpenChange={v=>{if(!v){setSelected(null);history.replaceState(null,'','/')}}}><DialogContent className="card-modal"><DialogTitle className="sr-only">{current?.name}卡牌详情</DialogTitle><DialogDescription className="sr-only">左侧为卡牌效果和字段，右侧为放大的卡图。</DialogDescription>{current&&<div className="detail-layout"><CardDetails card={current}/><div className="detail-art"><CardFace card={current} large/><a href={`/cards/${current.id}`} className="text-link">打开独立卡牌页面 <ArrowUpRight size={14}/></a></div></div>}</DialogContent></Dialog></div>
}




