'use client';
import {Sparkles,ArrowUpRight,Flame,Leaf,Droplets,Star,Moon,Orbit,Hexagon} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Card,categoryName,textValue,flagValue,cardAttribute,freeSlot,cardFields,cardFieldValue,fieldLabels,cardSource} from '@/lib/cards';
import {useSiteContent} from './site-provider';
import {CardFormat} from '@/lib/site-content';
import ArticleContent from './article-content';
export function CardFace({card:c,large=false,format}:{card:Card;large?:boolean;format?:CardFormat}){const {settings}=useSiteContent();const f=format||settings.formats[c.categoryId]||settings.formats.basic;return <div className={'card-face'+(large?' large-face':'')+(c.image?' has-image':'')} data-attribute={cardAttribute(c).replace(/^2/,'')} style={{aspectRatio:`${f.width}/${f.height}`,borderRadius:`${f.radius/f.width*100}% / ${f.radius/f.height*100}%`,'--card-ratio':f.width/f.height} as React.CSSProperties}>
{c.image?<img className="uploaded-card" src={c.image} alt={`${c.name}卡图`} loading={large?'eager':'lazy'} style={{objectPosition:`${c.imageX??50}% ${c.imageY??50}%`,transform:`scale(${c.imageScale??1})`,transformOrigin:`${c.imageX??50}% ${c.imageY??50}%`}}/>:<><div className="card-top"><b>{c.categoryId==='forbidden'?0:c.cost??'✦'}</b><span>{cardAttribute(c)||categoryName(c.categoryId)}</span></div><div className="card-placeholder"><Sparkles size={large?65:37}/><span>卡图待补</span><small>{f.height} × {f.width} mm</small></div><div className="card-face-caption"><small>{c.cardType||categoryName(c.categoryId)}</small><strong>{c.name}</strong><p>{c.effect||c.active||c.temple?.offering||'玛纳海姆档案'}</p></div></>}
</div>}
export function Tile({card:c,onClick}:{card:Card;onClick:()=>void}){return <button className="card-tile" onClick={onClick} aria-label={`查看${c.name}`}><CardFace card={c}/><div className="tile-caption"><span>{c.name}</span><ArrowUpRight size={15}/></div><p className="tile-meta">{c.cardType||categoryName(c.categoryId)}<i/>{cardAttribute(c)||'特殊卡牌'}</p>{c.categoryId==='forbidden'&&<div className="badges"><span>免费打出</span><span>{freeSlot(c)?'不占用禁咒区':'占禁咒区'}</span></div>}</button>}
export function Blocks({items}:{items:[string,any][]}){return <div className="info-blocks">{items.map(([title,value])=><section key={title}><h3>{title}</h3><p className="preserve">{textValue(value)}</p></section>)}</div>}
export function TempleTable({card:c}:{card:Card}){return <div className="temple-table"><p className="offering">每次供奉：献祭1张手牌 + {textValue(c.temple?.offering)}</p><Table><TableHeader><TableRow><TableHead>层数</TableHead><TableHead>奖励 / 效果</TableHead><TableHead>阶段</TableHead></TableRow></TableHeader><TableBody>{(c.temple?.levels||[]).map((l:any)=><TableRow key={l.level}><TableCell><b>{l.level===8?'8+':l.level}</b></TableCell><TableCell>{l.level===3&&<span className="gold-label">首次：补给手牌上限 +1<br/></span>}{textValue(l.reward,l.level===1?'无即时奖励':'未标注')}<small>{({2:'累计终局层数分：1VP',4:'累计终局层数分：3VP',6:'累计终局层数分：6VP',8:'累计终局层数分：11VP'} as any)[l.level]}</small></TableCell><TableCell><span className="stage-tag">{l.level===1?'无即时':l.level===3?'持续':l.level===7?'终局':l.level===8?'可重复':'即时'}</span></TableCell></TableRow>)}</TableBody></Table><p className="help">1 / 3 / 7 层无即时奖励。第3层持续效果在低于3层时失效；第7层需终局仍达到该层。每名玩家在每座殿的1–8层仅攀登一轮；到8层后可继续向上攀登虚拟层数，仍记作8层并领取顶层奖励。</p></div>}
export function Specialty({card:c}:{card:Card}){if(c.categoryId==='trick')return <Blocks items={[["触发条件",c.trick?.trigger||c.effect],["生效效果",c.trick?.effect],["业力",c.trick?.karmaText||c.trick?.karma],["生效分数",c.trick?.score??c.score]]}/>;if(c.categoryId==='tea')return <><Blocks items={[["全局效果",c.tea?.global],["举办人增益",c.tea?.host],["排名奖励",c.tea?.ranking],["弃置条件",c.tea?.discard||'未标注特殊弃置条件']]}/><div className="players-note"><strong>玩家人数与奖励</strong><p className="preserve">{textValue(c.tea?.players||c.playerCountRules,'原牌未标注人数调整，按牌面执行。')}</p></div></>;if(c.categoryId==='temple')return <TempleTable card={c}/>;if(c.categoryId==='bounty')return <Blocks items={[["达成条件",c.bounty?.condition||c.effect],["领取奖励",c.reward||'6VP + 1禁咒']]}/>;return null;}
export function CardDetails({card:c,character=false}:{card:Card;character?:boolean}){
 const {articles}=useSiteContent();const fields=cardFields(c.categoryId),isCharacter=character||c.categoryId==='witch';
 return <div className="detail-copy"><p className="eyebrow">{categoryName(c.categoryId)} <span>／ {c.id}</span></p><h1>{c.name}</h1>
 <div className="badges">{(c.effectTypes||[]).map((x:string)=><span key={x}>{x}</span>)}{c.categoryId==='forbidden'&&<><span>免费打出</span><span>{freeSlot(c)?'不占用禁咒区':'占禁咒区'}</span></>}</div>
 {isCharacter?<><p className="muted preserve">{c.nameRaw!==c.name?c.nameRaw?.split('\n').slice(1).join('\n'):cardAttribute(c)}</p><Blocks items={[["主动技能 · 原文",c.active],["被动技能 · 原文",c.passive],["技能补充",c.detail],["配件",c.accessories||'待设计者补充'],["背景故事",c.background||'档案尚未收录，待设计者补充。'],["设计者备注 · 打法定位",c.designerNotes||'待设计者补充']]}/></>:<><Specialty card={c}/>{['basic','forbidden'].includes(c.categoryId)&&<section className="effect-text"><h2>卡牌效果</h2><p className="preserve">{textValue(c.effect)}</p></section>}</>}
 {fields.length>0&&<><h2>字段速览</h2><dl className="field-grid" aria-label="字段速览">{fields.map(key=><div key={key}><dt>{fieldLabels[key]}</dt><dd>{textValue(cardFieldValue(c,key))}</dd></div>)}</dl></>}
 <Blocks items={[["效果注解",c.annotations||'未补充注解。效果与特殊条件请以完整原文为准。'],["卡牌描述",c.flavor||'暂无描述'],["备注",c.notes||'暂无备注']]}/>
 {isCharacter&&articles.filter(a=>a.kind==='character'&&a.characterId===c.id).map(a=><section className="character-article" key={a.id}><ArticleContent article={a}/></section>)}
 {c.sampleImage&&<details className="source-sample"><summary>规则书示例图</summary><img src={c.sampleImage} alt={`${c.name}规则书示例，可能含多张牌和标注`}/><p className="help">教学示例可能含多张卡牌和数字标注，效果请以本页完整文本为准。</p></details>}
 <p className="source-credit">来源：{cardSource(c)}{c.updatedAt?' · 已更新':''}</p></div>
}
