import {env} from 'cloudflare:workers';
import {adminUser} from './admin-auth';
export {adminUser} from './admin-auth';
import {seedCards,Card,canonicalCard,categories,effects,expansions,cardSource,CATALOG_VERSION} from './cards';
import {migrateCatalog} from './catalog-migration';
import {z} from 'zod';
export function database(){if(!env.DB)throw new Error('资料库暂不可用');return env.DB;}
export async function publicCards(){await ensureCatalog();const rows=await database().prepare('SELECT id,published FROM card_edits WHERE published IS NOT NULL').all<{id:string;published:string}>();const map=new Map<string,Card>(seedCards.map(c=>[c.id,c]));for(const row of rows.results)map.set(row.id,displayCard(JSON.parse(row.published)));return Array.from(map.values());}
export async function draftCards(){await ensureCatalog();const rows=await database().prepare('SELECT id,draft,published,revision,updated_at FROM card_edits').all<any>();const map=new Map<string,Card>(seedCards.map(c=>[c.id,{...c,revision:0,hasDraft:false,published:true}]));for(const row of rows.results)map.set(row.id,{...displayCard(JSON.parse(row.draft)),revision:row.revision,hasDraft:row.draft!==row.published,published:!!row.published||seedCards.some(c=>c.id===row.id),updatedAt:row.updated_at});return Array.from(map.values());}
export async function ensureCatalog(){await migrateCatalog(database(),Object.fromEntries(seedCards.map(c=>[c.legacyId,c.id])),Object.fromEntries(categories.map(([id])=>[id,seedCards.filter(c=>c.categoryId===id).length])));}
export const displayCard=(c:Card):Card=>({...c,sourceLabel:cardSource(c),catalogVersion:CATALOG_VERSION});
const s=z.string().max(25000).nullable().optional();const n=z.union([z.number().finite(),z.string().max(300)]).nullable().optional();
const schema=z.object({id:z.string().regex(/^[a-z0-9-]{0,80}$/),name:z.string().trim().min(1).max(100),categoryId:z.enum(['basic','forbidden','trick','bounty','tea','temple','witch']),cardType:s,cost:n,attribute:s,score:n,prerequisite:s,effect:s,flavor:s,imageX:z.number().min(0).max(100).optional(),imageY:z.number().min(0).max(100).optional(),imageScale:z.number().min(1).max(3).optional(),image:z.string().regex(/^\/(?:api\/images\/[a-z0-9-]+\.(?:png|jpg|webp|gif)|rules\/image\d+\.(?:png|jpg))$/).nullable().optional(),expansion:z.enum(expansions).nullable().optional(),effectTypes:z.array(z.enum(effects)).max(effects.length),debuffFlag:z.boolean().nullable().optional(),piercingFlag:z.boolean().nullable().optional(),faceColor:s,actionCount:n,notes:s,annotations:s,active:s,passive:s,detail:s,background:s,accessories:s,designerNotes:s,trick:z.object({trigger:s,effect:s,karma:n,karmaText:s,score:n}).nullable().optional(),tea:z.object({global:s,host:s,ranking:s,discard:s,players:s}).nullable().optional(),temple:z.object({offering:s,levels:z.array(z.object({level:z.number().int().min(1).max(8),reward:s,label:s})).length(8)}).nullable().optional(),bounty:z.object({condition:s,reward:s,difficulty:z.enum(['低','中','高','需结合局面']),difficultyIsOfficial:z.boolean().optional()}).nullable().optional()});
export function validatedCard(value:unknown,original?:Card):Card{const clean=schema.parse(value);if(clean.categoryId==='temple'&&new Set(clean.temple?.levels.map(x=>x.level)).size!==8)throw new Error('魔神殿需要完整且不重复的八层');const merged:any={...original,...clean};
 for(const key of ['trick','tea','temple','bounty']){const incoming=(clean as any)[key];if(incoming&&typeof incoming==='object'){merged[key]={...original?.[key],...incoming};if(key==='temple')merged.temple.levels=incoming.levels.map((l:any)=>({...original?.temple?.levels.find((p:any)=>p.level===l.level),...l}));}}
 const seed=seedCards.find(c=>c.id===clean.id);if(seed&&!merged.originalText)merged.originalText={name:seed.name,effect:seed.effect,active:seed.active,passive:seed.passive,detail:seed.detail,reward:seed.reward,flavor:seed.flavor};
 const result=canonicalCard(merged);const specialized=clean.categoryId==='trick'?'trick':clean.categoryId==='tea'?'tea':clean.categoryId==='bounty'?'bounty':null;
 if(specialized&&original){const incoming=(clean as any)[specialized];const keys=Object.keys(incoming||{});if(keys.every(k=>JSON.stringify(incoming[k])===JSON.stringify(original[specialized]?.[k]))){result.effect=original.effect;result.reward=original.reward;result.playerCountRules=original.playerCountRules;}}
 return result;}
export async function guard(request:Request){if(!await adminUser())return Response.json({error:'只有指定管理员可以修改资料。'},{status:403});const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)return Response.json({error:'请求来源无效。'},{status:403});return null;}
export const noCache={'Cache-Control':'no-store'};

